server:
  port: 9502
spring:
  mvc:
    pathmatch:
      # swagger3.0需要：ant_path_matcher
      # springboot2.6后默认为：path_pattern_parser
      matching-strategy: ant_path_matcher
  application:
    name: tqzl-community
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.188:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"



