server:
  port: 9998
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      # swagger3.0需要：ant_path_matcher
      # springboot2.6后默认为：path_pattern_parser
      matching-strategy: ant_path_matcher
  application:
    name: tqzl-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"




