#spring:
#  profiles:
#    active: dev

# Spring
server:
  port: 9999

spring:
  application:
    name: service-gateway
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
#       预约模块
        - id: tqzl-appointment
          uri: lb://tqzl-appointment
          predicates:
            - Path=/tqzl-appointment/**
          filters:
            - StripPrefix=1
#        小区模块
        - id: tqzl-community
          uri: lb://tqzl-community
          predicates:
            - Path=/tqzl-community/**
          filters:
            - StripPrefix=1
#        系统模块
        - id: tqzl-system
          uri: lb://tqzl-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
#        认证模块
        - id: tqzl-auth
          uri: lb://tqzl-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://docs.spring.io"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
swagger:
  username: admin
  password: admin


