server:
  port: 9501
  mvc:
    pathmatch:
      # swagger3.0需要：ant_path_matcher
      # springboot2.6后默认为：path_pattern_parser
      matching-strategy: ant_path_matcher
spring:
  profiles:
    active: dev
  application:
    name: tqzl-appointment
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.159.133:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"

# swagger配置
tuwer-swagger:
  author: 'l1'
  title: 'testt'
  version: 'v1'
  base-package: ''


